version: "3.9"
services:
  api:
    build: .
#    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - ".:/code"
    ports:
      - 80:8000
    container_name: monateri
    command: uvicorn app:app --host 0.0.0.0 --reload
